name: CI

on:
  pull_request:

jobs:
  build-doc-and-doc-test:
    runs-on: ubuntu-latest
    env:
      HTML_DIR: ./_build/html
    steps:
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Checkout to docs repo
        uses: actions/checkout@v2
      - name: Build docs and run doctest
        run: |
          bash .github/scripts/make-doc.sh test